services:
  - type: web
    name: restaurant-app
    env: node
    buildCommand: pnpm install && npx prisma generate && pnpm run build
    startCommand: pnpm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
